#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>

// Provided by the C runtime; holds the process environment variables.
extern char **environ;

// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5

#define STRACE_PATH "/usr/bin/strace"

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

/*
 * Check whether a line looks like a strace -T output line.
 * A valid line contains a syscall name followed by a time in angle brackets,
 * e.g. "read(0, buf, 1) = 1 <0.000123>".
 * Returns 1 if the line looks valid, 0 otherwise.
 */
int checkline(char *line) {
    char *syscall_name = strrchr(line, '(');
    char *time_str = strrchr(line, '<');
    if (syscall_name && time_str) {
        return 1; // Valid line
    }
    return 0; // Invalid line
}

/*
 * Parse one strace -T output line.
 * line: input line (may be modified by parsing).
 * syscall_name: output buffer for the syscall name.
 * time: output pointer for the elapsed time in seconds.
 * Returns 0 on success, -1 if the line cannot be parsed.
 */
int parse_strace_line(char *line, char *syscall_name, double *time) {
    if(checkline(line)){
        // Extract syscall name: everything before the first '('.
        char *name_end = strrchr(line, '(');
        if (name_end) {
            size_t name_len = name_end - line;
            strncpy(syscall_name, line, name_len);
            syscall_name[name_len] = '\0';
        } else {
            return -1; // Invalid format
        }

        // Extract time: floating-point number inside the last '<...>'.
        char *time_start = strrchr(line, '<');
        if (time_start) {
            *time = atof(time_start + 1); // Convert to double
        } else {
            return -1; // Invalid format
        }
        return 0; // Success
    }else{
        return -1;
    }
}

/*
 * Add a syscall timing to the statistics table.
 * If the syscall has been seen before, accumulate its time;
 * otherwise create a new entry. Also updates the total time.
 */
void add_syscall(syscall_stats *stats, const char *name, double time) {
    int n = stats->count;
    // Check if syscall already exists
    for (int i = 0; i < n; i++) {
        if (strcmp(stats->stats[i].name, name) == 0) {
            stats->stats[i].time += time;
            stats->total_time += time;
            return;
        }
    }
    // Add new syscall
    if (n < MAX_SYSCALLS) {
        strcpy(stats->stats[n].name, name);
        stats->stats[n].time = time;
        stats->count++;
        stats->total_time += time;
    }
}

/*
 * Sort syscalls by accumulated time (descending) and print the top n.
 * Also prints each syscall's percentage of the total traced time.
 */
void print_top_syscalls(syscall_stats *stats, int n) {
    // Sort syscalls by time in descending order (simple bubble sort).
    for (int i = 0; i < stats->count - 1; i++) {
        for (int j = i + 1; j < stats->count; j++) {
            if (stats->stats[i].time < stats->stats[j].time) {
                syscall_stat temp = stats->stats[i];
                stats->stats[i] = stats->stats[j];
                stats->stats[j] = temp;
            }
        }
    }

    // Print top n syscalls
    printf("Top %d syscalls by time:\n", n);
    printf("%-20s %-10s %-10s\n", "Syscall", "Time(s)", "Percentage");
    for (int i = 0; i < n && i < stats->count; i++) {
        double percentage = (stats->stats[i].time / stats->total_time) * 100;
        printf("%-20s %-10.6f %-10.2f%%\n", stats->stats[i].name, stats->stats[i].time, percentage);
    }
}

/*
 * Resolve a command name to an absolute executable path.
 * command: the user-supplied command (e.g. "ls" or "/bin/ls").
 * abs_path: output buffer to store the resolved path.
 * size: size of abs_path buffer.
 * Returns 1 if a valid executable path was found, 0 otherwise.
 */
int find_command_abs_path(const char *command, char *abs_path, size_t size) {
    // Absolute path: use it directly.
    if (command[0] == '/') {
        strncpy(abs_path, command, size - 1);
        abs_path[size - 1] = '\0';
        return 1;
    }
    char *path_env = getenv("PATH");
    if (!path_env) return 0; // PATH not found

    char* path_copy = strdup(path_env);
    char* token = strtok(path_copy, ":");
    while (token) {
        snprintf(abs_path, size, "%s/%s", token, command);
        token = strtok(NULL, ":");
        if (access(abs_path, X_OK) == 0) {
            free(path_copy);
            return 1; // Found executable
        }
    }

    free(path_copy);
    return 0; // Executable not found
}


int main(int argc, char *argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <strace_output_file>\n", argv[0]);
        return EXIT_FAILURE;
    }
    char *cmd = argv[1];
    char *abs_path = malloc(1024);
    if(cmd[0] == '/'){
        // Absolute path
        strncpy(abs_path, cmd, 1024);
    }else{
        if (!find_command_abs_path(cmd, abs_path, 1024)) {
            fprintf(stderr, "Command not found: %s\n", cmd);
            free(abs_path);
            return EXIT_FAILURE;
        }
    }

    //建立管道
    int pipefd[2];
    pipe(pipefd);
    pid_t pid = fork();
    if (pid == 0) {
        // Child process: run strace
        close(pipefd[0]); // Close read end
        dup2(pipefd[1], STDOUT_FILENO); // Redirect stdout to pipe
        dup2(pipefd[1], STDERR_FILENO); // Redirect stderr to pipe
        close(pipefd[1]); // Close write end after duplicating
        char *strace_args[argc + 2];
        strace_args[0] = STRACE_PATH;
        strace_args[1] = "-T";
        for(int i = 1; i < argc; i++) {
            strace_args[i + 1] = argv[i];
        }
        strace_args[argc + 1] = NULL;
        execve(STRACE_PATH, strace_args, environ);
        perror("execve failed");
        exit(EXIT_FAILURE);
    }else{
        // Parent process: read strace output and analyze
        close(pipefd[1]); // Close write end
        FILE *stream = fdopen(pipefd[0], "r");
        if (!stream) {
            perror("fdopen failed");
            free(abs_path);
            return EXIT_FAILURE;
        }
        // 逐行解析
        syscall_stats stats = { .count = 0, .total_time = 0.0 };
        char line[1024];
        while (fgets(line, sizeof(line), stream)) {
            char syscall_name[64];
            double time;
            if (parse_strace_line(line, syscall_name, &time) == 0) {
                add_syscall(&stats, syscall_name, time);
            }else{
                // Invalid line, skip
                continue;
            }
        }        

        fclose(stream);
        print_top_syscalls(&stats, TOP_N);
        free(abs_path);

        // Wait for the child process to finish and check its exit status.
        int status;
        if (waitpid(pid, &status, 0) == -1) {
            perror("waitpid failed");
            return EXIT_FAILURE;
        }
        // If strace (the child) failed to run, report failure to the shell.
        if (WIFEXITED(status) && WEXITSTATUS(status) != 0) {
            return EXIT_FAILURE;
        }
    }

    return EXIT_SUCCESS;
}
